// AUTO-GENERATED by scripts/generate-icons.ts — do not edit by hand.
// Add an icon by placing its component in ./static and re-running:
//   pnpm generate-icons              regenerate from Figma, then rebuild this file
//   pnpm generate-icons:index        rebuild this file from ./static only
import { ArrowDown } from "./static/arrow-down";
import { ArrowLeft } from "./static/arrow-left";
import { ArrowRight } from "./static/arrow-right";
import { ArrowUp } from "./static/arrow-up";
import { Check } from "./static/check";
import { CheckCircle } from "./static/check-circle";
import { CheckCircleFill } from "./static/check-circle-fill";
import { ChevronDown } from "./static/chevron-down";
import { ChevronDownBold } from "./static/chevron-down-bold";
import { ChevronDownMiniBold } from "./static/chevron-down-mini-bold";
import { ChevronLeft } from "./static/chevron-left";
import { ChevronLeftBold } from "./static/chevron-left-bold";
import { ChevronLeftMiniBold } from "./static/chevron-left-mini-bold";
import { ChevronRight } from "./static/chevron-right";
import { ChevronRightBold } from "./static/chevron-right-bold";
import { ChevronRightMiniBold } from "./static/chevron-right-mini-bold";
import { ChevronUp } from "./static/chevron-up";
import { ChevronUpBold } from "./static/chevron-up-bold";
import { ChevronUpMiniBold } from "./static/chevron-up-mini-bold";
import { Circle } from "./static/circle";
import { CircleFill } from "./static/circle-fill";
import { CircleGrid } from "./static/circle-grid";
import { CircleXmark } from "./static/circle-xmark";
import { CircleXmarkFill } from "./static/circle-xmark-fill";
import { Crosshairs } from "./static/crosshairs";
import { Document } from "./static/document";
import { DocumentFill } from "./static/document-fill";
import { EllipsisHorizontal } from "./static/ellipsis-horizontal";
import { EllipsisVertical } from "./static/ellipsis-vertical";
import { Folder } from "./static/folder";
import { FolderFill } from "./static/folder-fill";
import { Gear } from "./static/gear";
import { GearFill } from "./static/gear-fill";
import { GridSquare } from "./static/grid-square";
import { Hexagon } from "./static/hexagon";
import { HexagonDot } from "./static/hexagon-dot";
import { HexagonFill } from "./static/hexagon-fill";
import { HexagonFillDot } from "./static/hexagon-fill-dot";
import { InfoCircle } from "./static/info-circle";
import { InfoCircleFill } from "./static/info-circle-fill";
import { Link } from "./static/link";
import { List } from "./static/list";
import { LockLocked } from "./static/lock-locked";
import { LockLockedFill } from "./static/lock-locked-fill";
import { LockUnlocked } from "./static/lock-unlocked";
import { LockUnlockedFill } from "./static/lock-unlocked-fill";
import { MagnifyingGlass } from "./static/magnifying-glass";
import { Minus } from "./static/minus";
import { Moon } from "./static/moon";
import { Pause } from "./static/pause";
import { PauseFill } from "./static/pause-fill";
import { Photo } from "./static/photo";
import { PhotoFill } from "./static/photo-fill";
import { Placeholder } from "./static/placeholder";
import { Play } from "./static/play";
import { PlayFill } from "./static/play-fill";
import { Plus } from "./static/plus";
import { Rectangle } from "./static/rectangle";
import { RectangleFill } from "./static/rectangle-fill";
import { RulerSquare } from "./static/ruler-square";
import { SidebarLeft } from "./static/sidebar-left";
import { SidebarRight } from "./static/sidebar-right";
import { SliderHorizontal } from "./static/slider-horizontal";
import { SliderVertical } from "./static/slider-vertical";
import { SquareGrid } from "./static/square-grid";
import { Star } from "./static/star";
import { StarFill } from "./static/star-fill";
import { StarFour } from "./static/star-four";
import { StarFourFill } from "./static/star-four-fill";
import { Sun } from "./static/sun";
import { TriangleExclamation } from "./static/triangle-exclamation";
import { TriangleExclamationFill } from "./static/triangle-exclamation-fill";
import { Viewfinder } from "./static/viewfinder";
import { Xmark } from "./static/xmark";

export const icons = {
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle-fill": CheckCircleFill,
  "chevron-down": ChevronDown,
  "chevron-down-bold": ChevronDownBold,
  "chevron-down-mini-bold": ChevronDownMiniBold,
  "chevron-left": ChevronLeft,
  "chevron-left-bold": ChevronLeftBold,
  "chevron-left-mini-bold": ChevronLeftMiniBold,
  "chevron-right": ChevronRight,
  "chevron-right-bold": ChevronRightBold,
  "chevron-right-mini-bold": ChevronRightMiniBold,
  "chevron-up": ChevronUp,
  "chevron-up-bold": ChevronUpBold,
  "chevron-up-mini-bold": ChevronUpMiniBold,
  circle: Circle,
  "circle-fill": CircleFill,
  "circle-grid": CircleGrid,
  "circle-xmark": CircleXmark,
  "circle-xmark-fill": CircleXmarkFill,
  crosshairs: Crosshairs,
  document: Document,
  "document-fill": DocumentFill,
  "ellipsis-horizontal": EllipsisHorizontal,
  "ellipsis-vertical": EllipsisVertical,
  folder: Folder,
  "folder-fill": FolderFill,
  gear: Gear,
  "gear-fill": GearFill,
  "grid-square": GridSquare,
  hexagon: Hexagon,
  "hexagon-dot": HexagonDot,
  "hexagon-fill": HexagonFill,
  "hexagon-fill-dot": HexagonFillDot,
  "info-circle": InfoCircle,
  "info-circle-fill": InfoCircleFill,
  "info-circle-xmark": CircleXmark,
  link: Link,
  list: List,
  "lock-locked": LockLocked,
  "lock-locked-fill": LockLockedFill,
  "lock-unlocked": LockUnlocked,
  "lock-unlocked-fill": LockUnlockedFill,
  "magnifying-glass": MagnifyingGlass,
  minus: Minus,
  moon: Moon,
  pause: Pause,
  "pause-fill": PauseFill,
  photo: Photo,
  "photo-fill": PhotoFill,
  placeholder: Placeholder,
  play: Play,
  "play-fill": PlayFill,
  plus: Plus,
  rectangle: Rectangle,
  "rectangle-fill": RectangleFill,
  "ruler-square": RulerSquare,
  "sidebar-left": SidebarLeft,
  "sidebar-right": SidebarRight,
  "slider-horizontal": SliderHorizontal,
  "slider-vertical": SliderVertical,
  "square-grid": SquareGrid,
  star: Star,
  "star-fill": StarFill,
  "star-four": StarFour,
  "star-four-fill": StarFourFill,
  sun: Sun,
  "triangle-exclamation": TriangleExclamation,
  "triangle-exclamation-fill": TriangleExclamationFill,
  viewfinder: Viewfinder,
  "x-mark": Xmark,
  xmark: Xmark,
} as const;
