// AUTO-GENERATED by scripts/generate-icons.ts — do not edit by hand.
// Add an icon by placing its component in ./static/<weight> and re-running:
//   pnpm generate-icons              regenerate from Figma, then rebuild this file
//   pnpm generate-icons:index        rebuild this file from ./static only
import { ArrowDown as BoldArrowDown } from "./static/bold/arrow-down";
import { ArrowLeft as BoldArrowLeft } from "./static/bold/arrow-left";
import { ArrowRight as BoldArrowRight } from "./static/bold/arrow-right";
import { ArrowUp as BoldArrowUp } from "./static/bold/arrow-up";
import { Check as BoldCheck } from "./static/bold/check";
import { CheckCircle as BoldCheckCircle } from "./static/bold/check-circle";
import { CheckCircleFill as BoldCheckCircleFill } from "./static/bold/check-circle-fill";
import { ChevronDown as BoldChevronDown } from "./static/bold/chevron-down";
import { ChevronLeft as BoldChevronLeft } from "./static/bold/chevron-left";
import { ChevronRight as BoldChevronRight } from "./static/bold/chevron-right";
import { ChevronUp as BoldChevronUp } from "./static/bold/chevron-up";
import { Circle as BoldCircle } from "./static/bold/circle";
import { CircleFill as BoldCircleFill } from "./static/bold/circle-fill";
import { CircleXmark as BoldCircleXmark } from "./static/bold/circle-xmark";
import { Crosshairs as BoldCrosshairs } from "./static/bold/crosshairs";
import { Document as BoldDocument } from "./static/bold/document";
import { DocumentFill as BoldDocumentFill } from "./static/bold/document-fill";
import { EllipsisHorizontal as BoldEllipsisHorizontal } from "./static/bold/ellipsis-horizontal";
import { EllipsisVertical as BoldEllipsisVertical } from "./static/bold/ellipsis-vertical";
import { Folder as BoldFolder } from "./static/bold/folder";
import { FolderFill as BoldFolderFill } from "./static/bold/folder-fill";
import { GridSquare as BoldGridSquare } from "./static/bold/grid-square";
import { Hexagon as BoldHexagon } from "./static/bold/hexagon";
import { HexagonFill as BoldHexagonFill } from "./static/bold/hexagon-fill";
import { InfoCircle as BoldInfoCircle } from "./static/bold/info-circle";
import { InfoCircleFill as BoldInfoCircleFill } from "./static/bold/info-circle-fill";
import { Link as BoldLink } from "./static/bold/link";
import { List as BoldList } from "./static/bold/list";
import { LockLocked as BoldLockLocked } from "./static/bold/lock-locked";
import { LockLockedFill as BoldLockLockedFill } from "./static/bold/lock-locked-fill";
import { LockUnlocked as BoldLockUnlocked } from "./static/bold/lock-unlocked";
import { LockUnlockedFill as BoldLockUnlockedFill } from "./static/bold/lock-unlocked-fill";
import { MagnifyingGlass as BoldMagnifyingGlass } from "./static/bold/magnifying-glass";
import { Minus as BoldMinus } from "./static/bold/minus";
import { Moon as BoldMoon } from "./static/bold/moon";
import { Pause as BoldPause } from "./static/bold/pause";
import { PauseFill as BoldPauseFill } from "./static/bold/pause-fill";
import { Photo as BoldPhoto } from "./static/bold/photo";
import { PhotoFill as BoldPhotoFill } from "./static/bold/photo-fill";
import { Placeholder as BoldPlaceholder } from "./static/bold/placeholder";
import { Play as BoldPlay } from "./static/bold/play";
import { PlayFill as BoldPlayFill } from "./static/bold/play-fill";
import { Plus as BoldPlus } from "./static/bold/plus";
import { Rectangle as BoldRectangle } from "./static/bold/rectangle";
import { RectangleFill as BoldRectangleFill } from "./static/bold/rectangle-fill";
import { RulerSquare as BoldRulerSquare } from "./static/bold/ruler-square";
import { SliderHorizontal as BoldSliderHorizontal } from "./static/bold/slider-horizontal";
import { SliderVertical as BoldSliderVertical } from "./static/bold/slider-vertical";
import { Star as BoldStar } from "./static/bold/star";
import { StarFill as BoldStarFill } from "./static/bold/star-fill";
import { Sun as BoldSun } from "./static/bold/sun";
import { TriangleExclamation as BoldTriangleExclamation } from "./static/bold/triangle-exclamation";
import { TriangleExclamationFill as BoldTriangleExclamationFill } from "./static/bold/triangle-exclamation-fill";
import { Viewfinder as BoldViewfinder } from "./static/bold/viewfinder";
import { Xmark as BoldXmark } from "./static/bold/xmark";
import { ArrowDown as NormalArrowDown } from "./static/normal/arrow-down";
import { ArrowLeft as NormalArrowLeft } from "./static/normal/arrow-left";
import { ArrowRight as NormalArrowRight } from "./static/normal/arrow-right";
import { ArrowUp as NormalArrowUp } from "./static/normal/arrow-up";
import { Check as NormalCheck } from "./static/normal/check";
import { CheckCircle as NormalCheckCircle } from "./static/normal/check-circle";
import { CheckCircleFill as NormalCheckCircleFill } from "./static/normal/check-circle-fill";
import { ChevronDown as NormalChevronDown } from "./static/normal/chevron-down";
import { ChevronLeft as NormalChevronLeft } from "./static/normal/chevron-left";
import { ChevronRight as NormalChevronRight } from "./static/normal/chevron-right";
import { ChevronUp as NormalChevronUp } from "./static/normal/chevron-up";
import { Circle as NormalCircle } from "./static/normal/circle";
import { CircleFill as NormalCircleFill } from "./static/normal/circle-fill";
import { CircleXmark as NormalCircleXmark } from "./static/normal/circle-xmark";
import { Crosshairs as NormalCrosshairs } from "./static/normal/crosshairs";
import { Document as NormalDocument } from "./static/normal/document";
import { DocumentFill as NormalDocumentFill } from "./static/normal/document-fill";
import { EllipsisHorizontal as NormalEllipsisHorizontal } from "./static/normal/ellipsis-horizontal";
import { EllipsisVertical as NormalEllipsisVertical } from "./static/normal/ellipsis-vertical";
import { Folder as NormalFolder } from "./static/normal/folder";
import { FolderFill as NormalFolderFill } from "./static/normal/folder-fill";
import { GridSquare as NormalGridSquare } from "./static/normal/grid-square";
import { Hexagon as NormalHexagon } from "./static/normal/hexagon";
import { HexagonFill as NormalHexagonFill } from "./static/normal/hexagon-fill";
import { InfoCircle as NormalInfoCircle } from "./static/normal/info-circle";
import { InfoCircleFill as NormalInfoCircleFill } from "./static/normal/info-circle-fill";
import { InfoCircleXmark as NormalInfoCircleXmark } from "./static/normal/info-circle-xmark";
import { Link as NormalLink } from "./static/normal/link";
import { List as NormalList } from "./static/normal/list";
import { LockLocked as NormalLockLocked } from "./static/normal/lock-locked";
import { LockLockedFill as NormalLockLockedFill } from "./static/normal/lock-locked-fill";
import { LockUnlocked as NormalLockUnlocked } from "./static/normal/lock-unlocked";
import { LockUnlockedFill as NormalLockUnlockedFill } from "./static/normal/lock-unlocked-fill";
import { MagnifyingGlass as NormalMagnifyingGlass } from "./static/normal/magnifying-glass";
import { Minus as NormalMinus } from "./static/normal/minus";
import { Moon as NormalMoon } from "./static/normal/moon";
import { Pause as NormalPause } from "./static/normal/pause";
import { PauseFill as NormalPauseFill } from "./static/normal/pause-fill";
import { Photo as NormalPhoto } from "./static/normal/photo";
import { PhotoFill as NormalPhotoFill } from "./static/normal/photo-fill";
import { Placeholder as NormalPlaceholder } from "./static/normal/placeholder";
import { Play as NormalPlay } from "./static/normal/play";
import { PlayFill as NormalPlayFill } from "./static/normal/play-fill";
import { Plus as NormalPlus } from "./static/normal/plus";
import { Rectangle as NormalRectangle } from "./static/normal/rectangle";
import { RectangleFill as NormalRectangleFill } from "./static/normal/rectangle-fill";
import { RulerSquare as NormalRulerSquare } from "./static/normal/ruler-square";
import { SliderHorizontal as NormalSliderHorizontal } from "./static/normal/slider-horizontal";
import { SliderVertical as NormalSliderVertical } from "./static/normal/slider-vertical";
import { Star as NormalStar } from "./static/normal/star";
import { StarFill as NormalStarFill } from "./static/normal/star-fill";
import { Sun as NormalSun } from "./static/normal/sun";
import { TriangleExclamation as NormalTriangleExclamation } from "./static/normal/triangle-exclamation";
import { TriangleExclamationFill as NormalTriangleExclamationFill } from "./static/normal/triangle-exclamation-fill";
import { Viewfinder as NormalViewfinder } from "./static/normal/viewfinder";
import { XMark as NormalXMark } from "./static/normal/x-mark";
import { Xmark as NormalXmark } from "./static/normal/xmark";

export const icons = {
  bold: {
    "arrow-down": BoldArrowDown,
    "arrow-left": BoldArrowLeft,
    "arrow-right": BoldArrowRight,
    "arrow-up": BoldArrowUp,
    check: BoldCheck,
    "check-circle": BoldCheckCircle,
    "check-circle-fill": BoldCheckCircleFill,
    "chevron-down": BoldChevronDown,
    "chevron-left": BoldChevronLeft,
    "chevron-right": BoldChevronRight,
    "chevron-up": BoldChevronUp,
    circle: BoldCircle,
    "circle-fill": BoldCircleFill,
    "circle-xmark": BoldCircleXmark,
    crosshairs: BoldCrosshairs,
    document: BoldDocument,
    "document-fill": BoldDocumentFill,
    "ellipsis-horizontal": BoldEllipsisHorizontal,
    "ellipsis-vertical": BoldEllipsisVertical,
    folder: BoldFolder,
    "folder-fill": BoldFolderFill,
    "grid-square": BoldGridSquare,
    hexagon: BoldHexagon,
    "hexagon-fill": BoldHexagonFill,
    "info-circle": BoldInfoCircle,
    "info-circle-fill": BoldInfoCircleFill,
    link: BoldLink,
    list: BoldList,
    "lock-locked": BoldLockLocked,
    "lock-locked-fill": BoldLockLockedFill,
    "lock-unlocked": BoldLockUnlocked,
    "lock-unlocked-fill": BoldLockUnlockedFill,
    "magnifying-glass": BoldMagnifyingGlass,
    minus: BoldMinus,
    moon: BoldMoon,
    pause: BoldPause,
    "pause-fill": BoldPauseFill,
    photo: BoldPhoto,
    "photo-fill": BoldPhotoFill,
    placeholder: BoldPlaceholder,
    play: BoldPlay,
    "play-fill": BoldPlayFill,
    plus: BoldPlus,
    rectangle: BoldRectangle,
    "rectangle-fill": BoldRectangleFill,
    "ruler-square": BoldRulerSquare,
    "slider-horizontal": BoldSliderHorizontal,
    "slider-vertical": BoldSliderVertical,
    star: BoldStar,
    "star-fill": BoldStarFill,
    sun: BoldSun,
    "triangle-exclamation": BoldTriangleExclamation,
    "triangle-exclamation-fill": BoldTriangleExclamationFill,
    viewfinder: BoldViewfinder,
    xmark: BoldXmark,
  },
  normal: {
    "arrow-down": NormalArrowDown,
    "arrow-left": NormalArrowLeft,
    "arrow-right": NormalArrowRight,
    "arrow-up": NormalArrowUp,
    check: NormalCheck,
    "check-circle": NormalCheckCircle,
    "check-circle-fill": NormalCheckCircleFill,
    "chevron-down": NormalChevronDown,
    "chevron-left": NormalChevronLeft,
    "chevron-right": NormalChevronRight,
    "chevron-up": NormalChevronUp,
    circle: NormalCircle,
    "circle-fill": NormalCircleFill,
    "circle-xmark": NormalCircleXmark,
    crosshairs: NormalCrosshairs,
    document: NormalDocument,
    "document-fill": NormalDocumentFill,
    "ellipsis-horizontal": NormalEllipsisHorizontal,
    "ellipsis-vertical": NormalEllipsisVertical,
    folder: NormalFolder,
    "folder-fill": NormalFolderFill,
    "grid-square": NormalGridSquare,
    hexagon: NormalHexagon,
    "hexagon-fill": NormalHexagonFill,
    "info-circle": NormalInfoCircle,
    "info-circle-fill": NormalInfoCircleFill,
    "info-circle-xmark": NormalInfoCircleXmark,
    link: NormalLink,
    list: NormalList,
    "lock-locked": NormalLockLocked,
    "lock-locked-fill": NormalLockLockedFill,
    "lock-unlocked": NormalLockUnlocked,
    "lock-unlocked-fill": NormalLockUnlockedFill,
    "magnifying-glass": NormalMagnifyingGlass,
    minus: NormalMinus,
    moon: NormalMoon,
    pause: NormalPause,
    "pause-fill": NormalPauseFill,
    photo: NormalPhoto,
    "photo-fill": NormalPhotoFill,
    placeholder: NormalPlaceholder,
    play: NormalPlay,
    "play-fill": NormalPlayFill,
    plus: NormalPlus,
    rectangle: NormalRectangle,
    "rectangle-fill": NormalRectangleFill,
    "ruler-square": NormalRulerSquare,
    "slider-horizontal": NormalSliderHorizontal,
    "slider-vertical": NormalSliderVertical,
    star: NormalStar,
    "star-fill": NormalStarFill,
    sun: NormalSun,
    "triangle-exclamation": NormalTriangleExclamation,
    "triangle-exclamation-fill": NormalTriangleExclamationFill,
    viewfinder: NormalViewfinder,
    "x-mark": NormalXMark,
    xmark: NormalXmark,
  },
} as const;
