/**
 * Generate custom Radix color scales as CSS variables.
 *
 * Reads named scales from colors.config.ts, runs the official Radix
 * custom-palette generator (scripts/vendor/generate-radix-colors.ts) for
 * light and dark appearances, and writes the configured output file in the
 * same format as the "copy CSS" output of https://www.radix-ui.com/colors/custom:
 * an sRGB block plus a wide-gamut OKLCH/display-p3 block behind @supports.
 *
 * Run: pnpm generate-colors
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import config from "../colors.config.ts";
import { generateRadixColors } from "./vendor/generate-radix-colors.ts";

type Generated = ReturnType<typeof generateRadixColors>;

const LIGHT_SELECTOR = ":root, .light, .light-theme";
const DARK_SELECTOR = ".dark, .dark-theme";

function scaleVars(indent: string, name: string, gen: Generated, gamut: "srgb" | "p3") {
  const solids = gamut === "srgb" ? gen.accentScale : gen.accentScaleWideGamut;
  const alphas = gamut === "srgb" ? gen.accentScaleAlpha : gen.accentScaleAlphaWideGamut;
  const surface = gamut === "srgb" ? gen.accentSurface : gen.accentSurfaceWideGamut;
  const indicator = solids[8];
  return [
    ...solids.map((v, i) => `${indent}--${name}-${i + 1}: ${v};`),
    "",
    ...alphas.map((v, i) => `${indent}--${name}-a${i + 1}: ${v};`),
    "",
    `${indent}--${name}-contrast: ${gen.accentContrast};`,
    `${indent}--${name}-surface: ${surface};`,
    `${indent}--${name}-indicator: ${indicator};`,
    `${indent}--${name}-track: ${indicator};`,
  ];
}

function appearanceCss(name: string, gen: Generated, selector: string) {
  return [
    `${selector} {`,
    ...scaleVars("  ", name, gen, "srgb"),
    `}`,
    ``,
    `@supports (color: color(display-p3 1 1 1)) {`,
    `  @media (color-gamut: p3) {`,
    `    ${selector} {`,
    ...scaleVars("      ", name, gen, "p3"),
    `    }`,
    `  }`,
    `}`,
  ].join("\n");
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const parts = [
  "/* AUTO-GENERATED by scripts/generate-colors.ts — do not edit by hand.",
  "   Edit colors.config.ts and re-run: pnpm generate-colors */",
  "",
];

for (const [name, accent] of Object.entries(config.scales)) {
  const shared = { accent, gray: config.gray };
  const light = generateRadixColors({
    appearance: "light",
    background: config.background.light,
    ...shared,
  });
  const dark = generateRadixColors({
    appearance: "dark",
    background: config.background.dark,
    ...shared,
  });
  parts.push(
    appearanceCss(name, light, LIGHT_SELECTOR),
    "",
    appearanceCss(name, dark, DARK_SELECTOR),
    "",
  );
}

const outPath = path.resolve(root, config.out);
await writeFile(outPath, parts.join("\n"));
console.log(
  `Wrote ${Object.keys(config.scales).length} scale(s) [${Object.keys(config.scales).join(", ")}] to ${path.relative(root, outPath)}`,
);
